### ISSUE TITLE
Comando: |template

### ISSUE THREAD

**Issue by joshlopes** [GameOnPortugal/discord-bot#15]
### Template

O comando |template vai permitir associar um canal a um template de perguntas. O ideal será este template para já começar por ser um YAML file. Guardamos na base de dados este tipo de associao.

Exemplo de yaml file:

```
name: anuncios_venda
questions:
  product:
       question: Qual é o nome do produto?
       label: Produto
  state:
      question: Qual é o estado do produto?
      label: Estado
  price:
     question: Qual é o preço do produto?
     label: Preço
  zone:
    question: Qual é a zona onde o produto se encontra?
    label: Zona
  dispatch:
    question: Desejas enviar por correio? Se sim quais são os serviços?
    label: Envio
  warranty:
    question: O produto está coberto por garantia? Se sim indica até quando.
    label: Garantia
```

Modelo base de dados:

Template
```
channelId: INT PRIMARY UNIQUE
template: STRING
```
